micronaut:
  application:
    name: tenancy
datasources:
  url: jdbc:h2:mem:devDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
  driverClassName: org.h2.Driver
  username: sa
  password: ''
hibernate:
  hbm2ddl:
    auto: update

grails:
  gorm:
    multiTenancy:
      mode: DISCRIMINATOR
      tenantResolverClass: 'io.micronaut.multitenancy.gorm.HttpHeaderTenantResolver'